In [1]:
import numpy as np
import pandas as pd

In [2]:
RawData=pd.read_csv('Social_Network_Ads.csv')

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [50]:
RawData.head(10)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

In [51]:
RawData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [3]:
RawData.shape

(400, 5)

In [49]:
print(RawData.Gender)

0        Male
1        Male
2      Female
3      Female
4        Male
        ...  
395    Female
396      Male
397    Female
398      Male
399    Female
Name: Gender, Length: 400, dtype: object


In [4]:
cat_to_num=pd.get_dummies(RawData.Gender)

In [5]:
final_dataset=pd.concat([RawData,cat_to_num],axis='columns')

In [6]:
final_dataset=final_dataset.drop(['Gender','Male'],axis='columns')

In [7]:
final_dataset.head()

User ID  Age  EstimatedSalary  Purchased  Female
0  15624510   19            19000          0       0
1  15810944   35            20000          0       0
2  15668575   26            43000          0       1
3  15603246   27            57000          0       1
4  15804002   19            76000          0       0

In [8]:
x=final_dataset.drop('Purchased',axis=1)
y=final_dataset.pop('Purchased')

In [9]:
x

User ID  Age  EstimatedSalary  Female
0    15624510   19            19000       0
1    15810944   35            20000       0
2    15668575   26            43000       1
3    15603246   27            57000       1
4    15804002   19            76000       0
..        ...  ...              ...     ...
395  15691863   46            41000       1
396  15706071   51            23000       0
397  15654296   50            20000       1
398  15755018   36            33000       0
399  15594041   49            36000       1

[400 rows x 4 columns]

In [10]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [11]:
#splitting the data inthe form of train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [12]:
x_test

User ID  Age  EstimatedSalary  Female
132  15725660   30            87000       0
309  15652400   38            50000       1
341  15776844   35            75000       0
196  15738448   30            79000       1
246  15638003   35            50000       1
..        ...  ...              ...     ...
146  15750839   27            96000       1
135  15578006   23            63000       0
390  15807837   48            33000       0
264  15600379   48            90000       0
364  15654456   42           104000       0

[100 rows x 4 columns]

In [13]:
x_train

User ID  Age  EstimatedSalary  Female
250  15810075   44            39000       1
63   15583681   32           120000       0
312  15733964   38            50000       1
159  15598840   32           135000       1
283  15663249   52            21000       1
..        ...  ...              ...     ...
323  15619465   48            30000       1
192  15779581   29            43000       0
117  15591433   36            52000       0
47   15776348   27            54000       1
172  15794661   26           118000       1

[300 rows x 4 columns]

In [14]:
y_test

132    0
309    0
341    0
196    0
246    0
      ..
146    1
135    0
390    1
264    1
364    1
Name: Purchased, Length: 100, dtype: int64

In [15]:
y_train

250    0
63     1
312    0
159    1
283    1
      ..
323    1
192    0
117    0
47     0
172    0
Name: Purchased, Length: 300, dtype: int64

In [16]:
#fearure scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [17]:
#training the model
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
model.fit(x_train,y_train)

KNeighborsClassifier()

In [18]:
y_pred=model.predict(x_test)

In [19]:
print(y_pred)

[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 1 1]


In [20]:
print(y_test)

132    0
309    0
341    0
196    0
246    0
      ..
146    1
135    0
390    1
264    1
364    1
Name: Purchased, Length: 100, dtype: int64


In [21]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[64,  4],
       [ 4, 28]], dtype=int64)

In [24]:
accuracy=((64+28)/(64+28+4+4))*100
precision=(64/(64+4))*100
recall=(64/(64+4))*100

In [25]:
accuracy

92.0

In [26]:
precision

94.11764705882352

In [27]:
recall

94.11764705882352

# Decision Tree Classification Model

In [29]:
from sklearn.tree import DecisionTreeClassifier
model_DT=DecisionTreeClassifier(criterion='entropy')
model_DT=model_DT.fit(x_train,y_train)

In [30]:
y_pred_DT=model_DT.predict(x_test)

In [34]:
cm_dt=confusion_matrix(y_pred_DT,y_test)
cm_dt

array([[64,  5],
       [ 4, 27]], dtype=int64)

In [33]:
y_pred#KNN model

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [35]:
y_pred_DT #Decision Tree model

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1], dtype=int64)

In [36]:
y_test

132    0
309    0
341    0
196    0
246    0
      ..
146    1
135    0
390    1
264    1
364    1
Name: Purchased, Length: 100, dtype: int64

# Random Forest Classification Model

In [38]:
from sklearn.ensemble import RandomForestClassifier
model_RFC=RandomForestClassifier(n_estimators=10,criterion='entropy')
model_RFC=model_RFC.fit(x_train,y_train)

In [39]:
y_pred_RFC=model_RFC.predict(x_test)

In [40]:
y_pred_RFC

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [42]:
y_pred_DT

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1], dtype=int64)

In [43]:
y_test

132    0
309    0
341    0
196    0
246    0
      ..
146    1
135    0
390    1
264    1
364    1
Name: Purchased, Length: 100, dtype: int64

In [45]:
cm_RFC=confusion_matrix(y_pred_RFC,y_test)

In [46]:
cm_RFC

array([[64,  3],
       [ 4, 29]], dtype=int64)

In [47]:
Accuracy= ((64+29)/(64+29+3+4))*100
Accuracy

93.0

In [48]:
print(cm)
print(cm_dt)
print(cm_RFC)

[[64  3]
 [ 4 29]]
[[64  5]
 [ 4 27]]
[[64  3]
 [ 4 29]]
