In [23]:
#importing the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [24]:
#importing the dataset
myData=pd.read_csv('house_data.csv')
myData

Living_Space(sqft)  No_Of_Bedrooms  No_Of_Bathrooms  \
0                   1340               3             1.00   
1                   1690               3             2.25   
2                   2720               2             1.00   
3                   1360               4             3.00   
4                   1800               3             2.00   
5                   4760               4             4.50   
6                   2238               3             2.25   
7                   1650               3             1.50   
8                   1780               3             1.00   
9                   2390               3             2.50   
10                  2210               3             2.50   
11                  1330               2             1.00   
12                  1780               3             1.00   
13                  1370               3             1.75   
14                  1360               5             2.00   
15                  2140               4             3.00   
16                  1890               3             2.00   
17                  1610               4             1.00   
18                  1060               2             1.00   
19                  1280               3             1.00   
20                  1400               4             1.75   
21                  4110               3             2.75   
22                  2240               5             2.50   
23                  1220               2             1.50   
24                  2200               3             2.25   
25                  1030               3             2.00   
26                  1760               3             1.75   
27                  1860               3             1.00   
28                  1520               3             1.75   
29                  2630               4             2.50   
...                  ...             ...              ...   
1169                1370               4             2.00   
1170                1510               4             2.50   
1171                3470               4             4.00   
1172                2350               3             2.50   
1173                1970               3             2.50   
1174                1810               3             1.75   
1175                1550               3             2.00   
1176                2790               3             2.50   
1177                1550               2             1.75   
1178                1920               4             3.25   
1179                2420               4             2.75   
1180                3240               4             2.50   
1181                1710               3             1.00   
1182                2880               4             2.50   
1183                1650               3             3.50   
1184                3030               4             2.25   
1185                1840               3             1.00   
1186                2080               3             1.00   
1187                2234               2             2.00   
1188                1270               2             1.00   
1189                1900               3             2.50   
1190                1790               3             1.75   
1191                1440               4             1.00   
1192                 960               2             1.00   
1193                1710               3             1.00   
1194                 890               2             1.00   
1195                2360               6             2.50   
1196                1630               5             2.75   
1197                1200               3             1.75   
1198                1160               2             1.00   

      Condition(on scale of 5)  Year_Build   Location      Price  
0                            3        1955  Bangalore   221900.0  
1                            3        1951  Bangalore   538000.0  
2                     

In [25]:
#importing labelEncode and onehotencoder
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()

In [26]:
#lableling the data set with the help of labelencoder
myDatalabel=myData
#myDatalabel
myDatalabel.Location=labelencoder.fit_transform(myDatalabel.Location)
myDatalabel

Living_Space(sqft)  No_Of_Bedrooms  No_Of_Bathrooms  \
0                   1340               3             1.00   
1                   1690               3             2.25   
2                   2720               2             1.00   
3                   1360               4             3.00   
4                   1800               3             2.00   
5                   4760               4             4.50   
6                   2238               3             2.25   
7                   1650               3             1.50   
8                   1780               3             1.00   
9                   2390               3             2.50   
10                  2210               3             2.50   
11                  1330               2             1.00   
12                  1780               3             1.00   
13                  1370               3             1.75   
14                  1360               5             2.00   
15                  2140               4             3.00   
16                  1890               3             2.00   
17                  1610               4             1.00   
18                  1060               2             1.00   
19                  1280               3             1.00   
20                  1400               4             1.75   
21                  4110               3             2.75   
22                  2240               5             2.50   
23                  1220               2             1.50   
24                  2200               3             2.25   
25                  1030               3             2.00   
26                  1760               3             1.75   
27                  1860               3             1.00   
28                  1520               3             1.75   
29                  2630               4             2.50   
...                  ...             ...              ...   
1169                1370               4             2.00   
1170                1510               4             2.50   
1171                3470               4             4.00   
1172                2350               3             2.50   
1173                1970               3             2.50   
1174                1810               3             1.75   
1175                1550               3             2.00   
1176                2790               3             2.50   
1177                1550               2             1.75   
1178                1920               4             3.25   
1179                2420               4             2.75   
1180                3240               4             2.50   
1181                1710               3             1.00   
1182                2880               4             2.50   
1183                1650               3             3.50   
1184                3030               4             2.25   
1185                1840               3             1.00   
1186                2080               3             1.00   
1187                2234               2             2.00   
1188                1270               2             1.00   
1189                1900               3             2.50   
1190                1790               3             1.75   
1191                1440               4             1.00   
1192                 960               2             1.00   
1193                1710               3             1.00   
1194                 890               2             1.00   
1195                2360               6             2.50   
1196                1630               5             2.75   
1197                1200               3             1.75   
1198                1160               2             1.00   

      Condition(on scale of 5)  Year_Build  Location      Price  
0                            3        1955         0   221900.0  
1                            3        1951         0   538000.0  
2                        

In [33]:
#assining the x variable
x=myDatalabel[['Living_Space(sqft)','No_Of_Bedrooms','No_Of_Bathrooms','Condition(on scale of 5)',
               'Year_Build','Location']].values
x

array([[1.340e+03, 3.000e+00, 1.000e+00, 3.000e+00, 1.955e+03, 0.000e+00],
       [1.690e+03, 3.000e+00, 2.250e+00, 3.000e+00, 1.951e+03, 0.000e+00],
       [2.720e+03, 2.000e+00, 1.000e+00, 3.000e+00, 1.933e+03, 0.000e+00],
       ...,
       [1.630e+03, 5.000e+00, 2.750e+00, 3.000e+00, 1.990e+03, 6.000e+00],
       [1.200e+03, 3.000e+00, 1.750e+00, 3.000e+00, 1.964e+03, 6.000e+00],
       [1.160e+03, 2.000e+00, 1.000e+00, 3.000e+00, 1.948e+03, 6.000e+00]])

In [34]:
#assigning the y variable
y=myDatalabel.Price
y

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
5       1230000.0
6        257500.0
7        291850.0
8        229500.0
9        323000.0
10       662500.0
11       468000.0
12       310000.0
13       400000.0
14       530000.0
15       650000.0
16       395000.0
17       485000.0
18       189000.0
19       230000.0
20       385000.0
21      2000000.0
22       285000.0
23       252700.0
24       329000.0
25       233000.0
26       937000.0
27       667000.0
28       438000.0
29       719000.0
          ...    
1169     274700.0
1170     900000.0
1171    1150000.0
1172     605000.0
1173     359000.0
1174     850000.0
1175     505000.0
1176     565000.0
1177     585000.0
1178     328000.0
1179     749950.0
1180     826000.0
1181     535000.0
1182     925000.0
1183     875000.0
1184     902000.0
1185     423000.0
1186     235000.0
1187     545000.0
1188     343000.0
1189     334950.0
1190     405000.0
1191     220000.0
1192     173000.0
1193     6

In [35]:
#importing onehotcoder
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(categorical_features=[5])

In [36]:
x=ohe.fit_transform(x).toarray()
x

array([[1.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 3.000e+00,
        1.955e+03],
       [1.000e+00, 0.000e+00, 0.000e+00, ..., 2.250e+00, 3.000e+00,
        1.951e+03],
       [1.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 3.000e+00,
        1.933e+03],
       ...,
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 2.750e+00, 3.000e+00,
        1.990e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.750e+00, 3.000e+00,
        1.964e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 3.000e+00,
        1.948e+03]])

In [37]:
x=x[:,1:]
x

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 3.000e+00,
        1.955e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 2.250e+00, 3.000e+00,
        1.951e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 3.000e+00,
        1.933e+03],
       ...,
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 2.750e+00, 3.000e+00,
        1.990e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.750e+00, 3.000e+00,
        1.964e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 3.000e+00,
        1.948e+03]])

In [38]:
#importing the liner regression model
from sklearn.linear_model import LinearRegression
createModel=LinearRegression()

In [39]:
#calculating the linear regression
createModel.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [42]:
#predicting the price of house
createModel.predict([[0,0,0,0,1,0,2000,2,3,2,2000]])

array([580401.41898544])

In [41]:
#checking how perfect is our model
createModel.score(x,y)

0.4919204347965042